[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[template.environment]
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "Add your Stripe publishable key here: pk_test_xxx"
  STRIPE_SECRET_KEY = "Add your Stripe secret key here: sk_test_xxx"
  STRIPE_WEBHOOK_SECRET = "[Optional] Add your webhook secret here: whsec_xxx"
